In [2]:
from bs4 import BeautifulSoup as soup
from requests import get

In [3]:
# the url or page from where to scrap the data.
url = "http://www.espncricinfo.com/rankings/content/page/211271.html"

In [9]:
response = get(url)  # checking the response from the server to get the entire page.

In [12]:
html_soup = soup(response.text, 'html.parser')  # to structure the entire code in html format using beautiful soup.

In [128]:
main_heading = html_soup.find_all('h1')[1].text

" ICC rankings for Tests, ODIs, T20 & Women's ODI and T20 "

In [127]:
rankings = html_soup.find_all('table', {'class':'StoryengineTable'})
formate = html_soup.find_all('div', {'class':'ciPhotoContainer'})[0].find_all('h3')

In [131]:
print('\t',main_heading, '\n')
for i, r in enumerate(rankings):
    print(formate[i].text)
    print(rankings[0].caption.text)

    
    tr = r.find_all('tr')
    
    i=0
    
    for t in tr:
        if i == 0:
            search = 'th'
        else:
            search = 'td'
            
        for c in t.findChildren(search):
            print('{0:20}'.format(c.text), end=' ')
        print()
        i += 1
    print("\n\n")

	  ICC rankings for Tests, ODIs, T20 & Women's ODI and T20

ICC Test Championship
26 July 2019
Team                 Matches              Points               Rating
India                32                   3631                 113
New Zealand          23                   2547                 111
South Africa         27                   2917                 108
England              36                   3778                 105
Australia            27                   2640                 98
Sri Lanka            37                   3462                 94
Pakistan             27                   2263                 84
West Indies          29                   2381                 82
Bangladesh           22                   1438                 65
Zimbabwe             9                    140                  16



ICC ODI Championship
26 July 2019
Team                 Matches              Points               Rating
England              54                   6745                 125
India                56                   6807                 122
New Zealand          42                   4709                 112
Australia            50                   5543                 111
South Africa         47                   5193                 110
Pakistan             49                   4756                 97
Bangladesh           46                   3963                 86
Sri Lanka            54                   4425                 82
West Indies          46                   3541                 77
Afghanistan          40                   2359                 59
Ireland              29                   1466                 51
Zimbabwe             35                   1538                 44
Netherlands          6                    222                  37
Scotland             11                   399                  36
Nepal                8                    152                  19
UAE                  15                   144                  10
PNG                  9                    50                   6



ICC Twenty20 Rankings
26 July 2019
Team                 Matches              Points               Rating
Pakistan             26                   7365                 283
England              16                   4253                 266
South Africa         16                   4196                 262
Australia            21                   5471                 261
India                29                   7549                 260
New Zealand          16                   4056                 254
Afghanistan          16                   3849                 241
Sri Lanka            18                   4093                 227
West Indies          22                   4957                 225
Bangladesh           16                   3525                 220
Nepal                14                   2818                 201
Scotland             11                   2185                 199
Zimbabwe             13                   2477                 191
UAE                  15                   2765                 184
Netherlands          12                   2196                 183
Ireland              21                   3834                 183
PNG                  22                   3834                 174
Oman                 5                    774                  155
Hong Kong            8                    1213                 152
Namibia              12                   1729                 144
Singapore            13                   1707                 131
Qatar                18                   2262                 126
Saudi Arabia         11                   1331                 121
Jersey               16                   1834                 115
Canada               8                    887                  111
Italy                12                   1326                 111
Kuwait               13                   1354                 104
Denmark              14                   1438                 103
Kenya                12                   1229                 102
Germany              18                   1527                 85
USA                  9                    758                  84
Botswana             14                   1142                 82
Ghana                10                   773                  77
Malaysia             21                   1620                 77
Uganda               14                   1069                 76
Austria              6                    439                  73
Norway               10                   709                  87
Nigeria              10                   708                  71
Guernsey             16                   1127                 70
Sweden               8                    465                  58
Tanzania             6                    334                  56
Luxembourg           6                    328                  55
Spain                9                    479                  53
Philippines          9                    433                  48
France               6                    267                  45
Belize               9                    377                  42
Peru                 9                    356                  40
Bahrain              7                    261                  37
Mexico               12                   426                  36
Fiji                 6                    210                  35
Panama               9                    291                  32
Belgium              9                    290                  32
Samoa                10                   318                  32
Japan                10                   317                  32
Costa Rica           8                    252                  32
Vanuatu              15                   469                  31
Argentina            12                   370                  31
Hungary              6                    180                  30
Mozambique           12                   352                  29
Thailand             14                   369                  26
Chile                10                   249                  25
Malawi               12                   297                  25
Israel               7                    173                  25
Bhutan               8                    180                  23
South Korea          10                   217                  22
Isle of Man          7                    149                  21
Finland              10                   200                  20
Malta                11                   158                  14
Bulgaria             5                    68                   14
Sierra Leone         5                    61                   12
Brazil               9                    108                  12
Maldives             11                   114                  10
Czech Republic       10                   91                   9
St Helena            12                   109                  9
Gibraltar            8                    35                   4
Myanmar              9                    23                   3
Indonesia            7                    3                    0
China                11                   0                    0
Gambia               6                    0                    0
Swaziland            6                    0                    0
Rwanda               6                    0                    0
Lesotho              6                    0                    0



ICC Women's ODI Team Rankings
26 July 2019
Team                 Matches              Points               Rating
Australia Women      28                   4121                 147
India Women          33                   4018                 122
England Women        36                   4368                 121
New Zealand Women    33                   3714                 113
South Africa Women   42                   4097                 98
West Indies Women    25                   2139                 86
Pakistan Women       29                   2272                 78
Sri Lanka Women      29                   1617                 56
Bangladesh Women     13                   632                  49
Ireland Women        10                   211                  21



ICC Women's T20 Team Rankings
26 July 2019
Team                 Matches              Points               Rating
Australia Women      31                   8819                 284
England Women        34                   9448                 278
New Zealand Women    32                   8837                 276
West Indies Women    31                   8086                 261
India Women          38                   9504                 250
South Africa Women   33                   8015                 243
Pakistan Women       39                   8874                 228
Sri Lanka Women      32                   6569                 205
Bangladesh Women     31                   5913                 191
Ireland Women        20                   3677                 184
Zimbabwe Women       28                   4337                 155
Thailand Women       40                   6044                 151
Scotland Women       12                   1725                 144
Nepal Women          19                   2425                 128
UAE Women            27                   3381                 125
PNG Women            22                   2737                 124
Samoa Women          15                   1816                 121
Uganda Women         34                   4103                 121
Kenya Women          14                   1427                 102
Tanzania Women       28                   2755                 98
Netherlands Women    13                   1114                 86
Indonesia Women      21                   1735                 83
Hong Kong Women      26                   1979                 76
Qatar Women          5                    368                  74
Namibia Women        34                   2458                 72
China Women          24                   1612                 67
Vanuatu Women        15                   734                  49
Argentina Women      14                   674                  48
Japan Women          10                   464                  46
Rwanda Women         15                   654                  44
Myanmar Women        10                   424                  42
Sierra Leone Women   12                   489                  41
Malaysia Women       36                   1428                 40
Kuwait Women         8                    309                  39
Germany Women        10                   380                  38
USA Women            4                    150                  38
Botswana Women       15                   555                  37
Oman Women           4                    145                  36
France Women         7                    253                  36
Brazil Women         18                   597                  33
Nigeria Women        12                   364                  30
South Korea Women    5                    136                  27
Bhutan Women         7                    167                  24
Denmark Women        5                    98                   20
Mexico Women         6                    100                  17
Mozambique Women     14                   202                  14
Singapore Women      12                   148                  12
Zambia Women         3                    34                   11
Malawi Women         7                    68                   10
Belgium Women        5                    43                   9
Chile Women          13                   86                   7
Peru Women           11                   1                    0
Lesotho Women        8                    0                    0
Fiji Women           12                   0                    0
Mali Women           6                    0                    0
Swaziland Women      4                    0                    0

In [126]:
t.findChildren??